### PR TITLE
pycrit: fix the broken of cli the `crit show ipcns.img`

### PR DESCRIPTION
**Pull request by time-river**
It will broken when the cli `crit show ipcns-shm-9.img` is executed, msg:
```
  {
      "magic": "IPCNS_SHM",
      "entries": [
          {
              "desc": {
                  "key": 0,
                  "uid": 0,
                  "gid": 0,
                  "cuid": 0,
                  "cgid": 0,
                  "mode": 438,
                  "id": 0
              },
              "size": 1048576,
              "in_pagemaps": true,
              "extra": Traceback (most recent call last):
    File "/usr/bin/crit", line 6, in <module>
      cli.main()
    File "/usr/lib/python3/dist-packages/pycriu/cli.py", line 412, in main
      opts["func"](opts)
    File "/usr/lib/python3/dist-packages/pycriu/cli.py", line 45, in decode
      json.dump(img, f, indent=indent)
    File "/usr/lib/python3.9/json/__init__.py", line 179, in dump
      for chunk in iterable:
    File "/usr/lib/python3.9/json/encoder.py", line 431, in _iterencode
      yield from _iterencode_dict(o, _current_indent_level)
    File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
      yield from chunks
    File "/usr/lib/python3.9/json/encoder.py", line 325, in _iterencode_list
      yield from chunks
    File "/usr/lib/python3.9/json/encoder.py", line 405, in _iterencode_dict
      yield from chunks
    File "/usr/lib/python3.9/json/encoder.py", line 438, in _iterencode
      o = _default(o)
    File "/usr/lib/python3.9/json/encoder.py", line 179, in default
      raise TypeError(f'Object of type {o.__class__.__name__} '
  TypeError: Object of type bytes is not JSON serializable
```
This is caused by `img['magic'][0]['extra']` which is bytes. I find
other load condtions, fix them at the same time. And, reformat some
code.

Signed-off-by: fu.lin <fulin10@huawei.com>

### CODE REVIEW

**Comment by adrianreber** [comment]
Thanks for the patch, but unfortunately it breaks our CI tests:
```
+ ./test/crit-recode.py
b'test/dump/zdtm/transition/fork/56/1/pipes-data.img' decode fails: 'str' object has no attribute 'decode'
b'test/dump/zdtm/transition/fork/56/1/pipes-data.img' pretty decode fails: 'str' object has no attribute 'decode'
b'test/dump/zdtm/transition/fork/8800/1/pipes-data.img' decode fails: 'str' object has no attribute 'decode'
b'test/dump/zdtm/transition/fork/8800/1/pipes-data.img' pretty decode fails: 'str' object has no attribute 'decode'
b'test/dump/zdtm/transition/fork/9061/1/pipes-data.img' decode fails: 'str' object has no attribute 'decode'
b'test/dump/zdtm/transition/fork/9061/1/pipes-data.img' pretty decode fails: 'str' object has no attribute 'decode'
FAIL
```

**Comment by time-river** [comment]
> Thanks for the patch, but unfortunately it breaks our CI tests:
> 
> ```
> + ./test/crit-recode.py
> b'test/dump/zdtm/transition/fork/56/1/pipes-data.img' decode fails: 'str' object has no attribute 'decode'
> b'test/dump/zdtm/transition/fork/56/1/pipes-data.img' pretty decode fails: 'str' object has no attribute 'decode'
> b'test/dump/zdtm/transition/fork/8800/1/pipes-data.img' decode fails: 'str' object has no attribute 'decode'
> b'test/dump/zdtm/transition/fork/8800/1/pipes-data.img' pretty decode fails: 'str' object has no attribute 'decode'
> b'test/dump/zdtm/transition/fork/9061/1/pipes-data.img' decode fails: 'str' object has no attribute 'decode'
> b'test/dump/zdtm/transition/fork/9061/1/pipes-data.img' pretty decode fails: 'str' object has no attribute 'decode'
> FAIL
> ```

got it.

**Review by adrianreber — APPROVED** [review]

**Comment by rst0git** [comment]
@time-river does the patch in https://github.com/checkpoint-restore/criu/pull/1453 work for you?

**Comment by time-river** [comment]
> @time-river does the patch in #1453 work for you?

nope. I try the code in my case, it still reports the same error.
Refers to [`codes.ignore_errors`](https://docs.python.org/3/library/codecs.html#codecs.ignore_errors), it just *ignored and encoding or decoding is continued without further notice*.

**Review by rst0git — APPROVED** [review]

**Comment by adrianreber** [comment]
Just saw that this breaks the crit-recode test of tcp-stream images:
```
  fedora01  root  /home/criu   master  
 #  python test/zdtm.py run -t zdtm/static/socket-tcp -k always
userns is supported
=== Run 1/1 ================ zdtm/static/socket-tcp
timens isn't supported on 5.11.15-300.fc34.x86_64
======================= Run zdtm/static/socket-tcp in h ========================
Start test
./socket-tcp --pidfile=socket-tcp.pid --outfile=socket-tcp.out
Run criu dump
Run criu restore
Send the 15 signal to  57
Wait for zdtm/static/socket-tcp(57) to die for 0.100000
======================= Test zdtm/static/socket-tcp PASS =======================
^[[A  fedora01  root  /home/criu   master  
 #  test/crit-recode.py 
b'test/dump/zdtm/static/socket-tcp/57/1/tcp-stream-2e8d9a.img'  encode fails: expected bytes-like object, not str
b'test/dump/zdtm/static/socket-tcp/57/1/tcp-stream-2e8d9a.img' pretty  encode fails: expected bytes-like object, not str
FAIL
```

**Comment by adrianreber** [comment]
See #1540 for possible fix

**Pull request merged**
