### PR TITLE
Try to fix zdtm socket test 8880 port conflict

### PR DESCRIPTION
**Pull request by Snorch**
This may make https://github.com/checkpoint-restore/criu/issues/1079 race less noisy.

### CODE REVIEW

**Review by adrianreber — APPROVED** [review]
Sounds like a good idea to have different ports for the tests as they can run in parallel.

**Review by rst0git — APPROVED** [review]

**Comment by avagin** [comment]
Don't we run tests in separate network namespaces?

**Comment by Snorch** [comment]
> Don't we run tests in separate network namespaces?

1) not all of them
```
test/zdtm/static/net_lock_socket_iptables.desc:    'flavor': 'h',
test/zdtm/static/netns_lock_iptables.desc:    'flavor': 'h',
test/zdtm/static/socket-tcpbuf.desc:{'flavor': 'h', 'opts': '--tcp-established', 'flags': 'nouser samens'}
test/zdtm/static/socket-tcp.desc:{'flavor': 'h', 'opts': '--tcp-established', 'flags': 'nouser samens'}
test/zdtm/static/socket-tcp-reuseport.desc:{'flavor': 'h ns uns', 'opts': '--tcp-established', 'flags': 'nouser samens'}
```
2) some test has network logic before test_init() like socket-tcp6.c.

**Comment by avagin** [comment]
@Snorch We execute each test in our zdtm "container":
https://github.com/checkpoint-restore/criu/blob/criu-dev/test/zdtm_ct.c#L108

It creates a separate net namespace. Did I miss something?

**Comment by Snorch** [comment]
> @Snorch We execute each test in our zdtm "container":
> https://github.com/checkpoint-restore/criu/blob/criu-dev/test/zdtm_ct.c#L108
> 
> It creates a separate net namespace. Did I miss something?

You are right, thanks for pointing that out, I had wrong impression that we run several tests in one zdtm_ct. Then we can close this pr as it would not help for sure.

**Pull request closed without merging**
