### PR TITLE
sk-unix: Add support for SOCK_SEQPACKET unix sockets

### PR DESCRIPTION
**Pull request by minhbq-99**
I adjusted some SOCK_STREAM cases to handle SOCK_SEQPACKET too.
I also added SOCK_SEQPACKET variants on unix stream socket tests.

### CODE REVIEW

**Comment by adrianreber** [comment]
I guess this is a follow up of #1680 where @avagin suggested this change. Thanks!

**Comment by mihalicyn** [comment]
@minhbq-99 great work! ;)

You've also deleting `test/zdtm/static/mntns-deleted-dst` file (which is empty). Do you really want to remove it in this series?

It's also good to play with and extend `test/zdtm/static/scm03.c` test with `SOCK_SEQPACKET` and check that SCM's works fine.

**Comment by minhbq-99** [comment]
> You've also deleting `test/zdtm/static/mntns-deleted-dst` file (which is empty). Do you really want to remove it in this series?

I remove the change with mntns-deleted-dst in the patch.

> It's also good to play with and extend `test/zdtm/static/scm03.c` test with `SOCK_SEQPACKET` and check that SCM's works fine.

I just added a `SOCK_SEQPACKET` variant for scm03.c by changing the sock_type from `SOCK_DRAM` to `SOCK_SEQPACKET`

**Comment by mihalicyn** [comment]
LGTM

Thanks!

**Review by mihalicyn — APPROVED** [review]

**Comment by avagin** [comment]
LGTM

**Pull request merged**
