### PR TITLE
zdtm: Refactor nested anonymous functions

### PR DESCRIPTION
**Pull request by rst0git**
Avoid map() and filter() because they can be hard to read and understand, particularly when they need lambda.

A list comprehension affords far greater clarity, and provides a concise and efficient way to create iterators.

### CODE REVIEW

**Comment by avagin** [comment]
It is the monument to the great Russian Poet ;)
Vladimir Mayakovsky

**Comment by avagin** [comment]
And @xemul thinks this is the best code what have ever written in Python. You just need to read it from the bottom to the top.

**Comment by rst0git** [comment]
> It is the monument to the great Russian Poet ;)

I did know that. Thank you for letting me know.

**Comment by avagin** [comment]
Cc: @kolyshkin

**Comment by rst0git** [comment]
```
################### 4 TEST(S) FAILED (TOTAL 359/SKIPPED 34) ####################
 * zdtm/static/netns-nf(ns)
 * zdtm/static/socket-tcp-closed-last-ack(ns)
 * zdtm/static/socket-tcp-reseted(ns)
 * zdtm/static/socket-tcp-syn-sent(ns)
##################################### FAIL #####################################
Makefile:27: recipe for target 'alpine' failed
make: *** [alpine] Error 1
```
It fails for Alpine but I'm not what is the reason.

**Comment by avagin** [comment]
> It fails for Alpine but I'm not what is the reason.

 Test zdtm/static/netns-nf FAIL at Can't find lib ldd required by /usr/lib/xtables/libxt_standard.so

**Comment by rst0git** [comment]
> Test zdtm/static/netns-nf FAIL at Can't find lib ldd required by /usr/lib/xtables/libxt_standard.so

This should be fixed now. Thanks for the pointer!

**Comment by avagin** [comment]
ping @xemul

**Pull request closed without merging**
