### PR TITLE
compel/test: Resolve missing includes

### LINKED ISSUE #1333: Fail to compile libcompel examples
The tutorial says:

> `Clone the repo, build the project by running make, then go to compel/test/$test_name directory and run make there. Running spy bynary runs the example.`

Running `make` succeed under criu/ as I installed the dependcies on my Ubuntu 18.04. But I got errors bellow when I tried to run `make` under compel/test/fdspy: 

> root@DESKTOP-SCDP791:/mnt/c/tools/criu/compel/test/fdspy# make
gcc -O2 -g -Wall -Werror -c -Wstrict-prototypes -fno-stack-protector -nostdlib -fomit-frame-pointer -ffreestanding -fpie -I ../../../compel/include/uapi -o parasite.o parasite.c
In file included from parasite.c:3:0:
../../../compel/include/uapi/compel/plugins/plugin-fds.h:4:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before fds_send_fd’
 extern int __must_check fds_send_fd(int fd);
                         ^~~~~~~~~~~
In file included from parasite.c:4:0:
../../../compel/include/uapi/compel/infect-rpc.h:9:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘compel_rpc_sync’
 extern int __must_check compel_rpc_sync(unsigned int cmd, struct parasite_ctl *ctl);
                         ^~~~~~~~~~~~~~~
../../../compel/include/uapi/compel/infect-rpc.h:10:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘compel_rpc_call’
 extern int __must_check compel_rpc_call(unsigned int cmd, struct parasite_ctl *ctl);
                         ^~~~~~~~~~~~~~~
../../../compel/include/uapi/compel/infect-rpc.h:11:25: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘compel_rpc_call_sync’
 extern int __must_check compel_rpc_call_sync(unsigned int cmd, struct parasite_ctl *ctl);
                         ^~~~~~~~~~~~~~~~~~~~
parasite.c: In function ‘parasite_daemon_cmd’:
parasite.c:18:3: error: implicit declaration of function ‘fds_send_fd’; did you mean ‘fds_recv_fd’? [-Werror=implicit-function-declaration]
   fds_send_fd(2);
   ^~~~~~~~~~~
   fds_recv_fd
cc1: all warnings being treated as errors
Makefile:28: recipe for target 'parasite.o' failed
make: *** [parasite.o] Error 1

Could anyone figure out what happens?

### PR DESCRIPTION
**Pull request by rst0git**
This PR adds missing include statements to compel test cases.

Resolves #1333

### CODE REVIEW

**Comment by rst0git** [comment]
cc: @0x7f454c46

Some of the warnings seem related to the changes in 1c0716924 (compel/criu: Add __must_check)

**Review by adrianreber — APPROVED** [review]

**Review by 0x7f454c46 — APPROVED** [review]
LGTM, non-related to this PR question: should we run those tests in CI?

**Comment by adrianreber** [comment]
:+1: to running the tests in CI.

**Comment by rst0git** [comment]
I've updated the PR to run those tests in CI.

**Comment by 0x7f454c46** [comment]
@rst0git Thanks!

**Pull request merged**
