### PR TITLE
x86/compel/fault-inject: bound features to test

### PR DESCRIPTION
**Pull request by mihalicyn**
Hi there :)

These patches aimed to fix the problem from the https://github.com/checkpoint-restore/criu/issues/1635 issue.

I've grabbed VM from Amazon and tested that it's working fine now. The problem was that after putting garbage into the pkru registers our victim's processes catch segfaults because they lose access to their own VMAs (see `arch_vma_access_permitted` function https://github.com/torvalds/linux/blob/5bfc75d92efd494db37f5c4c173d3639d4772966/arch/x86/include/asm/mmu_context.h#L207).

Thanks,
Alex

### CODE REVIEW

**Comment by mihalicyn** [comment]
Thanks to @adrianreber for a great report with very important details about processor type (without this information this problem was almost uncatchable!), Andrei (@avagin), and Kirill (@cyrillos) for helpful advice and support.

**Comment by adrianreber** [comment]
I have disabled the fault injection tests on circle ci. Can you re-enable the tests so that we see that this is fixed.

**Comment by mihalicyn** [comment]
> I have disabled the fault injection tests on circle ci. Can you re-enable the tests so that we see that this is fixed.

yep. Have done already ;)

**Comment by cyrillos** [comment]
ack

**Review by cyrillos — APPROVED** [review]

**Comment by adrianreber** [comment]
Unfortunately the tests were not run on EC2 this time. It does not seem possible to control it if a EC2 system is assigned or not. But if you say you were able to reproduce it, that sounds very promising.

But, all other tests are still working, so that is good. I don't know enough about low level details like in this change, but if CI is happy I am :+1:

**Comment by mihalicyn** [comment]
I've managed to get t3.small instance from amazon with `Intel(R) Xeon(R) Platinum 8175M CPU` and tested on it.
That's a funny story when I've ordered several t3 instances and one of five was with desired processor type. Yep, I'm crazy :)

Can we restart tests for this PR manually?

**Comment by adrianreber** [comment]
> I've managed to get t3.small instance from amazon with `Intel(R) Xeon(R) Platinum 8175M CPU` and tested on it. That's a funny story when I've ordered several t3 instances and one of five was with desired processor type. Yep, I'm crazy :)

No, I would call it dedicated :smile: 

> Can we restart tests for this PR manually?

I can try, but usually a test does not move to another platform on restarting. But I will try.

**Comment by 0x7f454c46** [comment]
Well done!

Nit: Could it go a bit up like this:
```
        hdr->xstate_bv &= XFEATURE_MASK_USER;
        hdr->xstate_bv &= ~XFEATURE_MASK_SUPERVISOR;
+       hdr->xstate_bv &= XFEATURE_MASK_FAULTINJ;
```
or am I misreading it?

**Comment by 0x7f454c46** [comment]
In theory, it would be nice to see this gone later:
```
	for (i = 0; i < XFEATURE_MAX; i++) {
		if (!compel_fpu_has_feature(i))
			hdr->xstate_bv &= ~(1 << i);
	}
```
but I remember the reason for it: compel doesn't have a helper to return `xfeatures_mask` and I was reluctant to add a generic helper for every platform that would be only needed by x86 fault-injection code. So a bit ugly hack here stays :-)

**Review by 0x7f454c46 — APPROVED** [review]
LGTM

**Comment by mihalicyn** [comment]
Nice failure
```
Complete!
yum config-manager --set-enabled powertools
yum install -y --allowerasing asciidoc gcc git gnutls-devel libaio-devel libasan libcap-devel libnet-devel libnl3-devel libselinux-devel make protobuf-c-devel protobuf-devel python3-devel python3-flake8 python3-PyYAML python3-future python3-protobuf xmlto
CentOS Stream 8 - PowerTools                     17 MB/s | 3.7 MB     00:00    
Extra Packages for Enterprise Linux 8 - x86_64   13 MB/s |  11 MB     00:00    
Extra Packages for Enterprise Linux Modular 8 - 3.2 MB/s | 980 kB     00:00    
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libgcc >= 8.5.0-6.el8 needed by gcc-8.5.0-6.el8.x86_64
  - nothing provides libgomp = 8.5.0-6.el8 needed by gcc-8.5.0-6.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Pull request merged**
