### PR TITLE
mips64: implement vdso_redirect_calls()

### PR DESCRIPTION
**Pull request by sunny868**

### CODE REVIEW

**Comment by 0x7f454c46** [comment]
Hi @sunny868, nice patch!
Please, put a SingOffBy in it.
And also, could you check that vdso tests are passing on mips, specifically the vdso-proxy one?
Thanks!

**Comment by sunny868** [comment]
I'm sorry , what's meaning of "Sing-off-by " ?
And I'm not check it but my colleague check it between two computers and can work normally. 
Because linux-4.19 have not support timens for mips arch until linux-5.4,so vdso tests and vdso-proxy test can't be run ok.

`[root@localhost criu]# ./test/zdtm.py run -t  /home/gysun/work/criu-pr/criu/test/zdtm/static/vdso-proxy.c`
`userns is supported`
`=== Run 1/1 ================ /home/gysun/work/criu-pr/criu/test/zdtm/static/vdso-proxy.c`
`timens isn't supported`
`mount(binfmt_misc): No such device##################################### FAIL #####################################`

**Comment by rppt** [comment]
> I'm sorry , what's meaning of "Sing-off-by " ?

We ask contributors to sign off the commits as described here:
https://github.com/checkpoint-restore/criu/blob/criu-dev/CONTRIBUTING.md#sign-your-work

**Comment by sunny868** [comment]
@rppt Sorry I made a low-level mistake

**Comment by 0x7f454c46** [comment]
> And I'm not check it but my colleague check it between two computers and can work normally.

That's a good check, probably still worth a shot with zdtm test.

> Because linux-4.19 have not support timens for mips arch until linux-5.4,so vdso tests and vdso-proxy test can't be run ok.

Those tests should work without timens support.
It seems that you are confused with `timens isn't supported`.
But I think the reason it fails is that you're trying to run
```
./test/zdtm.py run -t /home/gysun/work/criu-pr/criu/test/zdtm/static/vdso-proxy.c
```
instead of
```
./test/zdtm.py run -t zdtm/static/vdso-proxy
```

Anyway, the patch now LGTM.

**Review by 0x7f454c46 — APPROVED** [review]

**Comment by sunny868** [comment]
[root@localhost criu]# uname -a
Linux localhost.localdomain 4.19.73+ #2 SMP PREEMPT Fri May 15 11:29:21 CST 2020 mips64 mips64 mips64 GNU/Linux
[root@localhost criu]# ./test/zdtm.py run -t zdtm/static/vdso-proxy
userns is supported
=== Run 1/1 ================ zdtm/static/vdso-proxy
timens isn't supported
======================= Run zdtm/static/vdso-proxy in h ========================
Start test
./vdso-proxy --pidfile=vdso-proxy.pid --outfile=vdso-proxy.out
Run criu dump
Run criu restore
Send the 15 signal to  48
Wait for zdtm/static/vdso-proxy(48) to die for 0.100000
Removing dump/zdtm/static/vdso-proxy/48
======================= Test zdtm/static/vdso-proxy PASS =======================
======================= Run zdtm/static/vdso-proxy in ns =======================
Start test
./vdso-proxy --pidfile=vdso-proxy.pid --outfile=vdso-proxy.out
Run criu dump
=[log]=> dump/zdtm/static/vdso-proxy/100/1/dump.log
------------------------ grep Error ------------------------
(00.051267) 	Running ip route save
(00.052658) 	Running ip -6 route save
(00.053980) 	Running ip rule save
Command "save" is unknown, try "ip rule help".
(00.055253) Warn  (criu/net.c:1878): Check if "ip rule save" is supported!
------------------------ ERROR OVER ------------------------
Run criu restore
Send the 15 signal to  119
Wait for zdtm/static/vdso-proxy(119) to die for 0.100000
Removing dump/zdtm/static/vdso-proxy/100
======================= Test zdtm/static/vdso-proxy PASS =======================
====================== Run zdtm/static/vdso-proxy in uns =======================
Start test
./vdso-proxy --pidfile=vdso-proxy.pid --outfile=vdso-proxy.out
Run criu dump
=[log]=> dump/zdtm/static/vdso-proxy/187/1/dump.log
------------------------ grep Error ------------------------
(00.052525) 	Running ip route save
(00.053923) 	Running ip -6 route save
(00.056607) 	Running ip rule save
Command "save" is unknown, try "ip rule help".
(00.057920) Warn  (criu/net.c:1878): Check if "ip rule save" is supported!
------------------------ ERROR OVER ------------------------
Run criu restore
Send the 15 signal to  208
Wait for zdtm/static/vdso-proxy(208) to die for 0.100000
Removing dump/zdtm/static/vdso-proxy/187
======================= Test zdtm/static/vdso-proxy PASS =======================
[root@localhost criu]#

**Comment by sunny868** [comment]
vdso00 and vdso02 also is PASS. but vdso01 run info is:

`[root@localhost criu]# ./test/zdtm.py run -t zdtm/static/vdso01`
`Skipping zdtm/static/vdso01 (arch x86_64)`

**Comment by 0x7f454c46** [comment]
Good work. Thanks!

**Pull request merged**
