### PR TITLE
scripts: Remove Python 2 dependency for Fedora tests

### PR DESCRIPTION
**Pull request by rst0git**
In https://github.com/checkpoint-restore/criu/pull/751 have been removed some of the Python 2 packages that are installed in Fedora Dockerfiles. There are a few necessary changes to allow the tests to work in environment with Python 3 only.

cc @adrianreber

### CODE REVIEW

**Comment by adrianreber** [comment]
Thanks!

**Comment by avagin** [comment]
Why do tests in Travis pass without these changes?

**Comment by rst0git** [comment]
Because by installing `python-ipaddress` and `python-yaml` we install Python 2 and executable files with `#!/usr/bin/env python2` shebang are able to run. With these changes Python 2 is no longer installed and we use only Python 3 to run the tests.

**Comment by avagin** [comment]
I was thinking about something like this. Thanks you for clarifying.

**Pull request merged**
