### PR TITLE
ci/gha: consolidate jobs

### PR DESCRIPTION
**Pull request by kolyshkin**
~~This commit stems from fixing the issue of running github actions ci
for each pull request. This happens because the configuration states
that those jobs need to run on push and pull_request. As a result,
each PR have twice the amount of CI jobs.~~

~~The fix to the above problem is to limit the CI for pushes only
to main and criu-dev branches, and tags starting with v.~~

~~Now, instead of modifying this is 8 different files, let's consolidate
those jobs into one single file.~~

Consolidate ci jobs and perform some cleanups:
 - make job names more compact
 - s/ubuntu-latest/ubuntu-20.04/ to avoid warnings
 - dedup x86_64 jobs by using matrix
 - replace matrix.target name where it is not a make target

### CODE REVIEW

**Comment by adrianreber** [comment]
Thanks. I am trying to remember if there was a reason why I created a file for each test instead one file like you did in this PR. But I cannot remember. So maybe there was no reason :grin: 

Looks good. It seems this is also triggering the problem described in https://github.com/checkpoint-restore/criu/issues/1346 and https://github.com/checkpoint-restore/criu/issues/1317 which are unrelated to this PR.

I would say this can be merged.

**Comment by adrianreber** [comment]
Why the limitation to run only on `master` and `criu-dev`? If I create some random branch on my checkout which I would like to use to create a PR later, I really like that CI runs, locally on my account before opening the PR. That way I can fix CI errors before opening a PR.

Don't you think that is useful? Just curious if my approach is unusual?

**Comment by kolyshkin** [comment]
> If I create some random branch on my checkout which I would like to use to create a PR later, I really like that CI runs, locally on my account before opening the PR. That way I can fix CI errors before opening a PR.

It's a matter of personal taste I guess. I would create a draft / WIP PR to run CI, or, if I do not intend at all to merge it, I'd create a test PR in my own fork (not in this repo), as **I am** the only one interested in CI at this point. On the contrary, **everyone** is (or should be) interested in CI results from `master` and `criu-dev` branches, this is why we have those.

Surely, if a few people are working together on a feature and they have a branch for it in this repo, it makes sense to have CI for that branch. As I see we have some stable* branches here, so yeah you're probably right, let's do CI for all branches (at least while it's free).

**Comment by kolyshkin** [comment]
> Why the limitation to run only on master and criu-dev?

Oh, OK, now I know why. I created a PR against my own fork of repo (https://github.com/kolyshkin/criu/pull/1) and noticed that every job is run twice.

Now I realize this is not the same for this repo (unless someone create a branch in here and then a PR to merge it), and it's not common to create a PR in a forked repo (unless someone will fork criu for real, rather than for development).

So I am not sure what to do here. Perhaps we can add `*stable` and `wip/*` to the list, to avoid CI running twice as per above scenario. WDYT @adrianreber ?

**Comment by kolyshkin** [comment]
>  Perhaps we can add `*stable` and `wip/*` to the list

I took a look and these branches were last pushed to in 2018, so I guess it does not make sense to add those.

In any case, I think if there's a need to test more branches, we can trivially add it later, and if there's a need for a CI run, anyone can create a WIP/DNM/draft PR either here on in their own fork.

**Comment by adrianreber** [comment]
> > Perhaps we can add `*stable` and `wip/*` to the list
> 
> I took a look and these branches were last pushed to in 2018, so I guess it does not make sense to add those.
> 
> In any case, I think if there's a need to test more branches, we can trivially add it later, and if there's a need for a CI run, anyone can create a WIP/DNM/draft PR either here on in their own fork.

I don't like this change. I am happy with my current workflow. Push to a branch on my fork, wait for CI, create a PR if everything is green. Opening a PR against my fork seems unnecessary complicated. But that is just my workflow and I can deal with it if we want to change it. I am not in favour of this, but do not not merge this because of me. Maybe others agree that this is the right thing to do.

**Comment by kolyshkin** [comment]
> I don't like this change. I am happy with my current workflow. Push to a branch on my fork, wait for CI, create a PR if everything is green. Opening a PR against my fork seems unnecessary complicated. But that is just my workflow and I can deal with it if we want to change it. I am not in favour of this, but do not not merge this because of me. Maybe others agree that this is the right thing to do.

Sounds reasonable; PR updated; PTAL @adrianreber

**Comment by kolyshkin** [comment]
Fixed PR description and commit message. @adrianreber PTAL

**Comment by adrianreber** [comment]
@kolyshkin I really feel bad for so much discussion about this, but now CI does not run on push. If I understand GitHub Actions correctly the following means:
```
on:
  push:
    tags:
      - v*
    branches:
  pull_request:
```

Build on any pull request and only on pushes to tags starting with `v*`. This does not run on pushes to any other branch. Also not on pushes to `criu-dev`.

I would like to keep the existing:
```
on: [push, pull_request]
```

As far as I understood this PR, the change to not build on any push was your initial motivation for this PR and that would be completely gone.

**Comment by kolyshkin** [comment]
@adrianreber you're right, my initial motivation was to fix when the jobs run, and it seems this does not need fixing. With that gone, this is just a consolidation and cleanup. There's little sense in consolidation per se; as for cleanups, I'll do it separately.

Closing, and sorry for wasting your time.

**Pull request closed without merging**
