### PR TITLE
Release 3.17.1

### PR DESCRIPTION
**Pull request by adrianreber**
A couple of commits cherry-picked to fix a few bug reports from users in the current 3.17 release.

Fixes: #1886

CC: @Snorch @avagin

### CODE REVIEW

**Comment by avagin** [comment]
Could you cherry-pick https://github.com/checkpoint-restore/criu/pull/1861?

**Comment by avagin** [comment]
lgtm

**Comment by adrianreber** [comment]
Also added #1879 to fix a CI error

**Review by Snorch — APPROVED** [review]

**Comment by rst0git** [comment]
@adrianreber Would it be possible to fix the CI lint error as well (https://github.com/checkpoint-restore/criu/pull/1920)?

**Comment by adrianreber** [comment]
CI is happy. Should we merge this?

**Comment by avagin** [comment]
@adrianreber thanks for working on this

**Pull request merged**
