### PR TITLE
Release 3.17

### PR DESCRIPTION
**Pull request by adrianreber**
I prepared a possible 3.17 release. I took everything from `criu-dev` except the `flog/` changes.

I would like to add following PRs also for 3.17 once they are merged in `criu-dev`:

* https://github.com/checkpoint-restore/criu/pull/1622
* https://github.com/checkpoint-restore/criu/pull/1706
* https://github.com/checkpoint-restore/criu/pull/1726

Especially #1706 feels important as Fedora 36 and RHEL 9 needs it for to have a working version of CRIU. @mihalicyn do you need any help with the rseq PR?

@checkpoint-restore/maintainers anything else you would like to see in 3.17?

### CODE REVIEW

**Comment by mihalicyn** [comment]
IMHO, another important issue is https://github.com/checkpoint-restore/criu/issues/1707
I can try to prepare fast fix after rseq.

**Comment by adrianreber** [comment]
Updated the 3.17 PR with the latest commits from `criu-dev`.

**Comment by adrianreber** [comment]
Updated to latest `criu-dev` changes. Do we maybe want to make a release without `rseq()` support for now and make 3.17.1 once the `rseq()` changes are ready?

**Comment by avagin** [comment]
@adrianreber what is the urgency? @mihalicyn Can you give us an estimation of when rseq will be ready to be merged?

**Comment by avagin** [comment]
@adrianreber could you create a wiki page for this release? @dayatsin-amd would you like to suggest a name for this release?

**Comment by adrianreber** [comment]
> @adrianreber what is the urgency?

I was hoping for a release in January as some of the changes are needed for crun and Podman. If `rseq()` needs more time, although it would be important to have it, maybe we should move it to the next release.

**Comment by dayatsin-amd** [comment]
> @adrianreber could you create a wiki page for this release? @dayatsin-amd would you like to suggest a name for this release?

@avagin Thank you for asking. I do not have a name in mind, please go ahead a pick a name :)

**Comment by rst0git** [comment]
> please go ahead a pick a name :)

What about "Golden Oriole"?

**Comment by dayatsin-amd** [comment]
> > please go ahead a pick a name :)
> 
> What about "Golden Oriole"?

Sounds good to me. That's a nice looking bird :)

**Comment by xemul** [comment]
2.5 was oriole already

**Comment by rst0git** [comment]
> 2.5 was oriole already

What about "Golden Pheasant"?

**Comment by mihalicyn** [comment]
@adrianreber we talked with Andrei about rseq series (https://github.com/checkpoint-restore/criu/pull/1706)
and he discovered and pointed out that possibly there are workloads when the patch [clone-noasan: unregister rseq at the thread start for new glibc](https://github.com/checkpoint-restore/criu/pull/1706/commits/d1f12a63cc23b1d42888341d37113b2f90468dc9) may lead to problems with glibc (for instance with malloc allocator). We have not full information or reproducer but it looks not fully safe solution just to unregister rseq without taking into account possible rseq users from the glibc side. I have no another solution for this problem. I need to dive into Glibc internals another time and investigate how to unregister rseq without risks. This may take extra time and I think it's better not to delay the release because of my slowness. I'm sorry about that. :(

**Comment by adrianreber** [comment]
@mihalicyn Good idea reaching out to Florian. He should be able to help you understand how it works.

**Comment by fweimer-rh** [comment]
@mihalicyn Is this unregistration needed before beginning with restore operation? Then I don't think this is an issue because at the end of the restore, the initial glibc will be gone from the process. But you must de-register rseq with the kernel because the restore might not have a replacement rseq registration.

**Comment by mihalicyn** [comment]
> @mihalicyn Is this unregistration needed before beginning with restore operation? Then I don't think this is an issue because at the end of the restore, the initial glibc will be gone from the process. But you must de-register rseq with the kernel because the restore might not have a replacement rseq registration.

1. This unregistration is needed because CRIU will unmap all memory of restorable processes and replace it with the original mappings from the images. So, if we leave rseq registered restorable process may get `SIGSEGV` from the kernel side when rseq will try to access `struct rseq` in the process memory.
Example: https://github.com/torvalds/linux/blob/ce522ba9ef7e2d9fb22a39eb3371c0c64e2a433e/kernel/rseq.c#L89
I've caught that crash in real practice.

2. we can't ignore possible problems from "quiet" rseq unregistration because when CRIU clones processes and threads during process tree restoration, it uses glibc heavily to restore file descriptors and other resources. Memory mappings restoration is performed almost at the end as well as processes executables replacement procedure.

Speaking generally, the restoration process looks like that (I'm omitting a lot of not necessary for our particular case details):
1. criu restores process tree by forking tasks in the desired hierarchy
2. each cloned task performs desired `open()`/`socket()`/etc syscalls to restore file descriptors
3. each cloned tasks performs all misc actions which can be done before memory is restored
4. tasks jumps to restorer pie (it will restore memory contents, exe magic link on procfs, environment variables contents and so on)

3. And yes, we need to unregister rseq from glibc to perform registration of actual rseq from the original user processes (if it was registered at all)

Generic task restore: https://github.com/checkpoint-restore/criu/blob/7d7d25f946e10b00c522dc44eb9c60d9eba2e7a0/criu/cr-restore.c#L866
Jumping to restorer pie: https://github.com/checkpoint-restore/criu/blob/7d7d25f946e10b00c522dc44eb9c60d9eba2e7a0/criu/cr-restore.c#L3813
Memory content restore: https://github.com/checkpoint-restore/criu/blob/7d7d25f946e10b00c522dc44eb9c60d9eba2e7a0/criu/pie/restorer.c#L1527
Executable setting: https://github.com/checkpoint-restore/criu/blob/7d7d25f946e10b00c522dc44eb9c60d9eba2e7a0/criu/pie/restorer.c#L1682

**Comment by mihalicyn** [comment]
I have a new idea. We can try to unregister rseq not just after clone(), but in the restorer pie just before `unmap_old_vmas`. When restorable processes dive into the restorer they never return into the Glibc-ied CRIU binary (it means that it's okay that we break rseq). So we can safely unregister rseq here.

**Comment by fweimer-rh** [comment]
> I have a new idea. We can try to unregister rseq not just after clone(), but in the restorer pie just before `unmap_old_vmas`. When restorable processes dive into the restorer they never return into the Glibc-ied CRIU binary (it means that it's okay that we break rseq). So we can safely unregister rseq here.

Yes, this is what I was about to suggest. Once you start unregistering kernel resources, you must not call into glibc again. This applies to older system calls as well, like `set_robust_list` and `set_thread_area` (or `arch_prctl` with `ARCH_SET_FS`).

**Comment by mihalicyn** [comment]
Thanks a lot, Florian. Then I will sit and write an implementation right now. :)

**Comment by mihalicyn** [comment]
It's ready https://github.com/checkpoint-restore/criu/pull/1706/commits/2ae7581e0b15f4a751e5c1e14da90e0fd65f1a4c

**Comment by dayatsin-amd** [comment]
> > please go ahead a pick a name :)
> 
> @dayatsin-amd what about Radiant Redstart? Since we're adding support for re(d)start-able sequences 😛

Sure, I am ok with Radiant Redstart :)

**Comment by rst0git** [comment]
Would it be possible to add https://github.com/checkpoint-restore/criu/pull/1738 in this release as well?

**Comment by adrianreber** [comment]
PR updated to include all latest `criu-dev` commits.

**Comment by avagin** [comment]
Could you cherry-pick cfacd86a4b8c83b2be9b503b401aaf1397c67c9e to this pr?

**Comment by avagin** [comment]
We need to create https://criu.org/Download/criu/3.17. I know @mihalicyn was ready to help with it.

**Comment by mihalicyn** [comment]
Sure, I've created a release page. Friends, please take a look at it. Possibly, I missed some improvements or fixes which we have to list on the release page.

**Review by rst0git — APPROVED** [review]
LGTM

**Review by Snorch — APPROVED** [review]
Looks good. And thanks a lot for merging mount engine patches!

**Comment by adrianreber** [comment]
> Sure, I've created a release page. Friends, please take a look at it. Possibly, I missed some improvements or fixes which we have to list on the release page.

Thanks for the wiki page. Looks good!

**Review by kolyshkin — APPROVED** [review]
SGTM

**Review by mihalicyn — APPROVED** [review]
LGTM

**Review by 0x7f454c46 — APPROVED** [review]
No concerns from my side, LGTM.

**Review by avagin — APPROVED** [review]

**Pull request merged**
