### PR TITLE
Refactor criu plugin baseline v2

### PR DESCRIPTION
**Pull request by rerrabolu**

### CODE REVIEW

**Comment by rerrabolu** [comment]
My changelist fails for two scenarios:

1. Cirrus CI / Vagrant Fedora Rawhide based test
2. Cirrus CI / Vagrant Fedora based test (no VDSO)

Is it possible for me to re-run them as the "details" does not show me if my change is the cause. Furthermore, I see other changelists that are having failures in the same validating element.

**Comment by avagin** [comment]
@dayatsin-amd friendly ping

**Comment by rst0git** [comment]
@rerrabolu Would it be possible to add tests that can be used to verify the functionality on a system with GPU?

**Comment by rerrabolu** [comment]
- Thanks for taking time to merge my issue.
- I see some lint errors, will try to provide a patch to address it next couple of weeks
- I will find out if we could add a small test case to validate CRIU on a system with AMD GPUs. This will take sometime and will require some coordination

**Comment by rst0git** [comment]
@rerrabolu Some of the lint errors have been fixed in https://github.com/checkpoint-restore/criu/pull/2345.

I have been using the example applications from the following repository for testing locally with an MI100 GPU:
https://github.com/ROCm/HIP-Examples/tree/master/HIP-Examples-Applications

The amdgpu plugin is [already enabled](https://github.com/checkpoint-restore/criu/pull/2276) in CI and perhaps we could add a few simple test cases to the [ZDTM test suite](https://criu.org/ZDTM_test_suite).

**Pull request merged**
