### PR TITLE
GSoC 19: Optimizing the Pre-dump Algorithm

### PR DESCRIPTION
**Pull request by criupatchwork**
This patch series implements optimization of pre-dumping algorithm
as part of GSoC 2019 project.

In current pre-dumping, the target process needs to be frozen
till all the memory pages are drained into pipes. Then the target
process gets unfrozen and pages collected into pipes are written
into image files at the end of pre-dump. This approach has two
problems. First, target process remains frozen for longer duration.
Second, pipes induce memory pressure in the system. If memory
utilization during pre-dump is nearly equal to system's memory,
then this risks running into out-of-memory failures as the pipe
pages are not reclaimable.

The new implementation of pre-dump solves above mentioned two
issues. In this, the target process is frozen untill memory
mappings are collected. Then the process will unfreeze and
continue. The pages of target process are copied while process
is running. We use process_vm_readv syscall to copy pages from
process memory to user-space buffer, by using collected mappings.
Since page copying and process execution are happening
simultaneously, there is possibility that process might have
modified some mappings after they have been collected. This
results in race over memory mappings.

This patch series handles the race over mappings, utilizes
user-space buffer through process_vm_readv syscall to copy pages
and reduces the frozen time for target process by allowing it to
run as soon as memory mappings are collected. We call this new
approach of pre-dumping as "read mode pre-dump". New CLI option
--pre-dump-mode is added for it, which takes "splice" or "read"
as input. "splice" mode is traditional parasite way of pre-dumping
and is set by default.

Evaluation of new approach:
---------------------------

Performance:
------------
$ ./test/zdtm.py run --pre 5 -t zdtm/static/maps04 -f h

Splice mode -
pre-dump: 0.59
pre-dump: 0.06
pre-dump: 0.07
pre-dump: 0.06
pre-dump: 0.06
dump: 0.12

$ ./test/zdtm.py run --pre 5 -t zdtm/static/maps04 --pre-dump-mode=read -f h

Read mode -
pre-dump: 0.66
pre-dump: 0.06
pre-dump: 0.06
pre-dump: 0.06
pre-dump: 0.06
dump: 0.12

Average drop : ~ 7%
Maximum drop : ~ 13%

Freeze time:
------------
$ ./test/zdtm.py run --pre 5 -t zdtm/static/maps04 --show-stats -f h

Splice mode -
pre-dump: 122235
pre-dump: 77514
pre-dump: 77912
pre-dump: 74940
pre-dump: 71977
dump: 131208

$ ./test/zdtm.py run --pre 5 -t zdtm/static/maps04 --pre-dump-mode=read --show-stats -f h

Read mode -
pre-dump: 82365
pre-dump: 67521
pre-dump: 68385
pre-dump: 68706
pre-dump: 67144
dump: 160998

Average reduction : ~18%
Maximum reduction : ~35%

Abhishek Dubey (7):
  Adding --pre-dump-mode option
  Skip generating iov for non-PROT_READ memory
  Skip adding PROT_READ to non-PROT_READ mappings
  Adding cnt_sub for stats manipulation
  Handle vmsplice failure for read mode pre-dump
  read mode pre-dump implementation
  Refactor time accounting macros

 Documentation/criu.txt    |   6 +
 criu/config.c             |  10 ++
 criu/cr-dump.c            |   9 +-
 criu/crtools.c            |   2 +
 criu/include/cr_options.h |   7 +
 criu/include/page-xfer.h  |   4 +
 criu/include/stats.h      |   1 +
 criu/mem.c                |  88 +++++++++--
 criu/page-pipe.c          |  10 ++
 criu/page-xfer.c          | 382 ++++++++++++++++++++++++++++++++++++++++++++++
 criu/stats.c              |  12 ++
 test/zdtm.py              |   9 +-
 12 files changed, 524 insertions(+), 16 deletions(-)

### CODE REVIEW

**Comment by avagin** [comment]
@Snorch we read pagemap, create a list of all pages that have to be dumped then clear soft-dirty bits, unfreeze processes and start dumping pages. Where is a race here?

**Comment by Snorch** [comment]
@avagin Thanks for explanation! Now I see that it is enough to lock only "soft-dirty clear + pagemap-read" to have consistent pre-dumps.

Another problem comes in mind, again - may be I'm missing something. What if: we dumped pagemap of the process and released it, now we are dumping it's pages. Then process dies and another process reuses it's pid? Syscall process_vm_readv works on pid number, so it won't fill any difference and we will continue reading pagemap. Assume we are "lucky" and the new process has exactly the same page offsets in it's pagemap. We will produce a predump filled with inconsistent combination of two processes. Now more, the second process had all pages with cleaned soft dirty, because it was forked from other process which pagemap was just read and bits were cleared. These means that on final dump we will use pages from the predump.

The "lucky" process may be an attacker which tries to steel memory form the first process.

**Comment by 0x7f454c46** [comment]
@Snorch Yeah, that's a good concern.

Probably, we could check at least the creation time for a process to verify that's the same one (as we do between pre-dumps now..)
I wish we could use pidfd instead though

**Comment by avagin** [comment]
> These means that on final dump we will use pages from the inconsistent predump.

We will not. On the final dump, we will detect that this process has died. I am agree that we have an issue here. A user can request to dump their processes tree and then they will receive images with some memory of other processes.

We can use pidfd and check that a target process is still alive after dumping all pages. If it is not, we can remove all its images.

**Comment by Snorch** [comment]
Yes, we can fix it either with:
1) holding open pidfd on the process to check if it is still alive and memory is valid;
or
2) checking that process creation time is strictly less than the time of pagemap reed (under freeze "lock") for a (pre-)dump, which makes these (pre-)dump valid.

**Comment by avagin** [comment]
@Snorch could you file a new issue to this and assigned it to @dubeyabhishek? Thanks.

**Comment by Snorch** [comment]
@avagin 
>We will not.

>checking that process creation time is strictly less than the time of pagemap reed (under freeze "lock") for a (pre-)dump, which makes these (pre-)dump valid.

After looking into the code I see that inventory_save_uptime() and __parasite_dump_pages_seized()->generate_vma_iovs() and __parasite_dump_pages_seized()->task_reset_dirty_track() are still all done then all tasks are frozen. So our current detect_pid_reuse() should make it's job fine for an optimized pre-dump too.

Sorry that I didn't get it from the beginning...

**Comment by Snorch** [comment]
> I am agree that we have an issue here. A user can request to dump their processes tree and then they will receive images with some memory of other processes.

>could you file a new issue to this

Now when I've rethought everything... These optimization makes pre-dump possibly containing memory of other processes, yes. But may be it's not an issue? - Same thing will happen if we do the pre-dump a bit later, it will contain different data and possibly of different processes. We can't freeze everything immediately anyway, isn't it?

So no issue and we are fine, OK?

**Comment by avagin** [comment]
Applied.

**Pull request closed without merging**
