### PR TITLE
3.16 Makefile.versions

### PR DESCRIPTION
**Pull request by adrianreber**
CI is green. This would be the Makefile changes for the 3.16 release.

Amongst a huge number of fixes all over the place and the move away from
Travis this release introduces:

* better support for restoring containers into existing pods
* pidfd based pid reuse detection for RPC clients
* allow restoring of precreated veth devices
* license change for all files in the images/ directory to MIT
* criu-ns helper script
* use clang-format for automatic code indentation
* support checkpoint/restore of stacked apparmor profiles
* [GSoC] Add nftables based network locking/unlocking (Zeyad Yasser)

### CODE REVIEW

**Comment by adrianreber** [comment]
The only CI error with this PR is due to a broken container image. The OpenJ9 latest container image is currently ppc64le only. The x86_64 part of the image has not been uploaded to the registry.

**Comment by rst0git** [comment]
> The only CI error with this PR is due to a broken container image. The OpenJ9 latest container image is currently ppc64le only. The x86_64 part of the image has not been uploaded to the registry.

I've opened a PR to update the container image: https://github.com/checkpoint-restore/criu/pull/1615

**Comment by kolyshkin** [comment]
@adrianreber can you please rebase?

**Comment by avagin** [comment]
@kolyshkin I cherry-picked e68d75054244434b1d5b2f26f55d22aa6cfb8e54 to the master.

**Pull request merged**
