### PR TITLE
crtools: ignore SIGPIPE in swrk mode

### PR DESCRIPTION
**Pull request by liusdu**
Signed-off-by: Liu Hua <weldonliu@tencent.com>

### CODE REVIEW

**Comment by avagin** [comment]
LGTM

nit: It would be good to add a few lines in the commit message to explain why we need this for swrk.

**Comment by adrianreber** [comment]
The CentOS 8 error should go away after a rebase.

**Comment by liusdu** [comment]
@avagin @adrianreber rebased and add commit message~

**Review by rst0git — APPROVED** [review]
LGTM

**Pull request merged**
