### PR TITLE
Prepare the next release

### PR DESCRIPTION
**Pull request by avagin**
https://criu.org/Download/criu/3.18

### CODE REVIEW

**Comment by avagin** [comment]
@ymanton I suggest you to invent a name for this release.

**Comment by ymanton** [comment]
How about "Unprivileged Otter" or "Rootless Robot"?

**Comment by rst0git** [comment]
@ymanton The release codename format is "*\<material\> \<bird breed\>*".
Here is the list of previous releases: https://criu.org/Download/criu

**Comment by ymanton** [comment]
Ah thanks.

"Plastic Parrot"?

"Silver Sandpiper"?

**Comment by adrianreber** [comment]
Looks like you selected the wrong destination branch for this PR. Thanks for doing it. Looks good.

**Comment by Snorch** [comment]
`git check-rebase  origin/master..origin/criu-dev origin/master..avagin-3.18-release` is clean meaning that all patches from v3.18-part1 branch were rebased without conflicts.

```
git check-rebase origin/master..avagin-3.18-release origin/master..origin/criu-dev | grep "^\s"
           6f8d5435b  Add flog to CRIU
           bf7b517fd  flog: Missing varargs init or cleanup (VARARGS)
           09348a277  Run 'make indent' on 'flog/'
           d355c3681  flog: typo: mmaped -> mmapped
           6eafe4ea7  flog: fix some codespell warnings
           03539d4d3  ci: Fix unsafe repository error
           3c8aa309f  crit: Use same version as criu
           be6d7ca8e  page-pipe: fix limiting a pipe size
           d84e2e4e9  page-xfer: use negative values for error codes
           6d879d570  page-xfer: adjust a buffer to a pipe size
           a6aae071f  pre-dump: call vmsplice with SPLICE_F_GIFT
           574f39642  page-xfer: refactoring analyze_iov and fill_userbuf
           45641ab26  ci: test the read mode of pre-dump
           cd0ed7e54  amdgpu/Makefile: Fix include path
           2b3763fe6  amdgpu: Set PLUGINDIR to /usr/lib/criu
           ac2724513  mount-v2: split out restore_one_sharing helper
           7e3761865  mount-v2: workaround for multiple external bindmounts with no common root
           58a2d982d  zdtm: test multiple ext bindmounts with no common root and same master
           dc160c0d8  util/mount-v2: fix resolve_mountpoint() to always return freeable pointer
           f82b71c9c  zdtm: add mnt_root_ext test
           029ca2237  ci: Fix code indent
```
Here are the patches which are excluded from rebase (are in criu-dev, but not in v3.18-part1). I would vote at least for mount-v2 patches to be included, also some other patches seem useful too.

**Comment by avagin** [comment]
@Snorch all these patches are in the master branch already. They were a part of the 3.17 release.

**Comment by Snorch** [comment]
> all these patches are in the master branch already. They were a part of the 3.17 release.

You are right, I was assuming that criu-dev is based on v3.17.1, but it is on v3.17. That's why my above git-check-rebase was not doing what I wanted =)

```
[ criu]$ git check-rebase v3.17..origin/criu-dev v3.17..avagin-3.18-release | grep -v "^\S\{9\}\s\{2\}\S\{9\}\s\{2\}"
           d46f40f4f  criu: Version 3.17.1
[ criu]$ git check-rebase v3.17..avagin-3.18-release v3.17..origin/criu-dev | grep -v "^\S\{9\}\s\{2\}\S\{9\}\s\{2\}"
           6f8d5435b  Add flog to CRIU
           bf7b517fd  flog: Missing varargs init or cleanup (VARARGS)
           09348a277  Run 'make indent' on 'flog/'
           d355c3681  flog: typo: mmaped -> mmapped
           6eafe4ea7  flog: fix some codespell warnings
           ded46f6c9  net: fail restore if nftables isn't supported but image is present
```

Now it shows that everything is right.

**Review by Snorch — APPROVED** [review]

**Comment by rst0git** [comment]
Currently, when python 3.12 is used, `make install` would fail with the following error:
```
Traceback (most recent call last):
  File "/root/criu/scripts/crit-setup.py", line 2, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils'
make[1]: *** [lib/Makefile:62: install] Error 1
make: *** [Makefile.install:37: install-lib] Error 2
```

Would it make sense to include the patch from https://github.com/checkpoint-restore/criu/pull/2009 in this release?

**Comment by adrianreber** [comment]
We should rework c3a519272881bc36243d142427b8d9f2ddc46f82. That commit adds new required fields to `cgroup.proto` which breaks restoring images from all older CRIU versions. This should not be `required` but `optional`.

Someone just reported this to me.

**Comment by minhbq-99** [comment]
> We should rework [c3a5192](https://github.com/checkpoint-restore/criu/commit/c3a519272881bc36243d142427b8d9f2ddc46f82). That commit adds new required fields to `cgroup.proto` which breaks restoring images from all older CRIU versions. This should not be `required` but `optional`.
> 
> Someone just reported this to me.

Hi, I created a PR to fix this: https://github.com/checkpoint-restore/criu/pull/2128

**Review by rst0git — APPROVED** [review]
LGTM

**Pull request merged**
