### PR TITLE
Prepare v3.19

### PR DESCRIPTION
**Pull request by avagin**
* The loongarch64 support
* membarrier() registration c/r
* Many fixes and improvements from the Google team
* Drop python 2 compatibility
* Support XSAVE on newer Intel CPUs
* Fixes here and there

@znley I suggest you to choose a name for this release.

### CODE REVIEW

**Comment by rst0git** [comment]
@avagin Would it be possible to include the patch from https://github.com/checkpoint-restore/criu/pull/2282 in this release?

**Comment by avagin** [comment]
@rst0git I will add it when it is merged to criu-dev.

**Comment by znley** [comment]
Daming Rosefinch

Thank you for your invitation. This name comes from a novel I like. Rosefinch is a mythical animal and Daming Rosefinch is a sword shaped like rosefinch, its Chinese name is "大明朱雀". What is your oponion?

**Comment by rst0git** [comment]
> Daming Rosefinch

The word "daming" at first glance looks very similar to [_damning_](https://dictionary.cambridge.org/dictionary/english/damning), which has a slightly different meaning.

**Comment by znley** [comment]
> What do you think about "Vermilion Rosefinch"?

A pretty good suggestion. If similarity to _damning_ is not acceptable, _Vermilion Rosefinch_ is the best choice.

**Review by osctobe — APPROVED** [review]

**Comment by avagin** [comment]
> This name comes from a novel I like. Rosefinch is a mythical animal and Daming Rosefinch is a sword shaped like rosefinch, its Chinese name is "大明朱雀". What is your oponion?

@znley The format is "material"/"bird breed". Here is the list of all previous releases https://criu.org/Download/criu

**Comment by znley** [comment]
@avagin 
It was only after your reminder that I realized the first word was "material". "Bronez Peacock"  should comply with this rule.

**Review by 0x7f454c46 — APPROVED** [review]
Don't see anything concerning from my POV. LGTM.

**Comment by Snorch** [comment]
1) (minor nit) maybe we can merge https://github.com/checkpoint-restore/criu/commit/6d0e785182 to https://github.com/checkpoint-restore/criu/commit/af31e8e242 as the former is just a fixup. (note: comment style there is also wrong, so we might also want to fix it while at it)
2) we lack Signed-off-by in https://github.com/checkpoint-restore/criu/commit/347c6a8bf @avagin @yota9 

Except that, looks good.

**Comment by avagin** [comment]
> we lack Signed-off-by in 347c6a8bf @avagin @yota9

@yota9 can I add your sign-off to this commit?

**Comment by yota9** [comment]
Sure, thank you very much and sorry for that

**Pull request merged**
