### PR TITLE
ci: Update vagrant VM to Fedora 34

### PR DESCRIPTION
**Pull request by rst0git**
Fedora 34 was released on April 27, 2021. This PR updates the vagrant build to run tests on the new release.

### CODE REVIEW

**Comment by adrianreber** [comment]
On Fedora 34 the tun_ns tests seems to fail. I have seen this before, but I do not remember what triggers it.

**Comment by rst0git** [comment]
> On Fedora 34 the tun_ns tests seems to fail. I have seen this before, but I do not remember what triggers it.

Thanks for pointing it out. This issue looks related to https://github.com/checkpoint-restore/criu/issues/747

```
```

**Comment by rst0git** [comment]
> On Fedora 34 the tun_ns tests seems to fail. I have seen this before, but I do not remember what triggers it.

@adrianreber I opened another pull request to fix this problem https://github.com/checkpoint-restore/criu/pull/1490

**Comment by adrianreber** [comment]
Please rebase

**Pull request merged**
