### PR TITLE
uffd: call disconnect_from_page_server to shutdown a page-server connection

### LINKED ISSUE #1380: lazy-thp: fail at criu page-server
#### Description

The `lazy-thp` test fails when running in an Alpine container. (https://github.com/checkpoint-restore/criu/pull/1277)

#### Steps to reproduce the issue:

```sh
sudo podman run -it --rm \
    --privileged \
    --mount type=tmpfs,tmpfs-size=512M,destination=/tmp \
    --mount type=tmpfs,tmpfs-size=512M,destination=/run \
    --network=host \
    --cgroupns=host \
    -v /lib/modules:/lib/modules \
    alpine sh
```

```sh
apk update && apk add \
gcc \
bash \
build-base \
coreutils \
git \
gnutls-dev \
libaio-dev \
libcap-dev \
libnet-dev \
libnl3-dev \
nftables \
nftables-dev \
pkgconfig \
protobuf-c-dev \
protobuf-dev \
py3-pip \
py3-protobuf \
python3 \
ip6tables \
iptables \
nftables \
iproute2 \
bash \
e2fsprogs \
py-yaml \
tar

pip3 install junit_xml

git clone https://github.com/checkpoint-restore/criu
cd criu && make -j4
ln -s /usr/bin/python3 /usr/bin/python
python3 ./test/zdtm.py run -t zdtm/transition/lazy-thp --remote-lazy-pages --tls
```

#### Describe the results you received:
```
====================== Run zdtm/transition/lazy-thp in h =======================
Start test
./lazy-thp --pidfile=lazy-thp.pid --outfile=lazy-thp.out
Run criu dump
=[log]=> dump/zdtm/transition/lazy-thp/141/1/dump.log
------------------------ grep Error ------------------------
b'(00.007220) Parasite syscall_ip at 0x560878ee0000'
b'(00.007546) Set up parasite blob using memfd'
b'(00.007634) Putting parasite blob into 0x7f6766617000->0x7f38ddd28000'
b'(00.007749) Dumping general registers for 141 in native mode'
b'(00.007759) Warn  (compel/arch/x86/src/lib/infect.c:341): Will restore 141 with interrupted system call'
------------------------ ERROR OVER ------------------------
Run criu page-server
Run criu lazy-pages
Run criu restore
Send the 15 signal to  141
Wait for zdtm/transition/lazy-thp(141) to die for 0.100000
=[log]=> dump/zdtm/transition/lazy-thp/141/1/page-server.log
------------------------ grep Error ------------------------
b'(00.000705) Running status-ready scripts'
b'(00.018805) Accepted connection from 127.0.0.1:32936'
b'(00.056929) tls: TLS handshake completed'
b'(00.057853) page-pipe: Created tee pipe size 4194304'
b'(00.065013) Error (criu/tls.c:319): tls: Pull callback recv failed: Connection reset by peer'
b'(00.065038) Error (criu/tls.c:146): tls: Failed receiving data: Error in the pull function.'
b"(00.065048) Error (criu/page-xfer.c:1193): page-xfer: Can't read pagemap from socket: I/O error"
b'(00.065062) Error (criu/tls.c:307): tls: Push callback send failed: Broken pipe'
------------------------ ERROR OVER ------------------------
##### Test zdtm/transition/lazy-thp FAIL at criu page-server exited with 1 #####
Test output: ================================
12:36:52.025:   141: PASS

 <<< ================================
##################################### FAIL #####################################
```

[page-server.log](https://github.com/checkpoint-restore/criu/files/7727299/page-server.log.txt)
[lazy-pages.log](https://github.com/checkpoint-restore/criu/files/7727297/lazy-pages.log.txt)
[dump.log](https://github.com/checkpoint-restore/criu/files/7727295/dump.log.txt)
[restore.log.txt](https://github.com/checkpoint-restore/criu/files/7727300/restore.log.txt)

### PR DESCRIPTION
**Pull request by avagin**
Fixes #1380

### CODE REVIEW

**Comment by rst0git** [comment]
@avagin could please apply the following patch?

```diff
--- a/criu/uffd.c
+++ b/criu/uffd.c
@@ -1358,6 +1358,7 @@ static int lazy_sk_hangup_event(struct epoll_rfd *rfd)
 {
        if (!restore_finished) {
                pr_err("Restorer unexpectedly closed the connection\n");
+               disconnect_from_page_server();
                return -1;
        }
 
```

**Comment by avagin** [comment]
I have changed the first patch to call disconnect_from_page_server unconditionally. In the ideal case, we need to introduce an async mode for it and use it on error paths.

**Review by rst0git — APPROVED** [review]
LGTM

Thank you Andrei!

**Comment by adrianreber** [comment]
I just had another TLS error during CI runs. The log is already gone. I try to link to it next time I see it.

**Comment by adrianreber** [comment]
Actually, not sure if this is related:
```
 ====================== Run zdtm/transition/lazy-thp in ns ======================
Start test
./lazy-thp --pidfile=lazy-thp.pid --outfile=lazy-thp.out
Run criu dump
=[log]=> dump/zdtm/transition/lazy-thp/143/1/dump.log
------------------------ grep Error ------------------------
b'(00.010287) Parasite syscall_ip at 0x55c8bdc6d000'
b'(00.010499) Set up parasite blob using memfd'
b'(00.010551) Putting parasite blob into 0x7f62f8254000->0x7f787c12f000'
b'(00.010630) Dumping general registers for 146 in native mode'
b'(00.010634) Warn  (compel/arch/x86/src/lib/infect.c:341): Will restore 146 with interrupted system call'
------------------------ ERROR OVER ------------------------
Run criu page-server
Run criu lazy-pages
Run criu restore
Send the 15 signal to  167
Wait for zdtm/transition/lazy-thp(167) to die for 0.100000
=[log]=> dump/zdtm/transition/lazy-thp/143/1/page-server.log
------------------------ grep Error ------------------------
b'(00.001030) Starting page server on port 12345'
b'(00.001054) Running status-ready scripts'
b'(00.036399) Accepted connection from 127.0.0.1:45670'
b'(00.036443) page-pipe: Created tee pipe size 4194304'
b"(00.047298) Error (criu/page-xfer.c:1193): page-xfer: Can't read pagemap from socket: Connection reset by peer"
------------------------ ERROR OVER ------------------------
##### Test zdtm/transition/lazy-thp FAIL at criu page-server exited with 1 #####
```

Maybe this helps: https://github.com/adrianreber/criu/runs/4688928142?check_suite_focus=true

**Comment by rst0git** [comment]
```
b'(00.001030) Starting page server on port 12345'
b'(00.001054) Running status-ready scripts'
b'(00.036399) Accepted connection from 127.0.0.1:45670'
b'(00.036443) page-pipe: Created tee pipe size 4194304'
b"(00.047298) Error (criu/page-xfer.c:1193): page-xfer: Can't read pagemap from socket: Connection reset by peer"
```

@adrianreber This error happens when the page-server is not using TLS.

**Pull request merged**
