### PR TITLE
README.md correct travis links

### PR DESCRIPTION
**Pull request by grooverdan**
Codacy is unfixed currently as it looks like it isn't getting updates.

### CODE REVIEW

**Comment by rppt** [comment]
@grooverdan, thanks for the fix.

We are old fashioned, though, and we send patches to criu@openvz.org mailing list rather than do GitHub pull requests.
Can you please send you patch to the list?

**Comment by grooverdan** [comment]
Its a bit to go though for a most likely once-off uncontentious URL fix. Especially for a not-so-old fashioned dev who remembers it was something to do with ```git format-patch``` and even then was only partially successful. I might get to it, but I'd really prefer not to have to.

**Comment by rst0git** [comment]
Hi @grooverdan

I send your patch to the mailing list
https://lists.openvz.org/pipermail/criu/2018-June/041767.html

FYI: `git send-email` makes it very easy to send a set patches to the mailing list. For example I send your patch with:
```
git send-email -1 --to criu@openvz.org --annotate --subject-prefix=PATCH
```

**Comment by avagin** [comment]
Thanks for all who were involved.
https://github.com/checkpoint-restore/criu/commit/b24a54b63ef8c8ba497f7e1b20bb8096add0abe3

**Comment by grooverdan** [comment]
thanks @rst0git

**Pull request closed without merging**
