### PR TITLE
MAINTAINERS: Add Pavel (myself) to maintainers

### PR DESCRIPTION
**Pull request by Snorch**
Hope I have enough experience in the project to be nominated. I want to help with review and will try to do my best in it.

### CODE REVIEW

**Comment by Snorch** [comment]
@avagin Thanks for your trust! I understand it, sure.

**Comment by avagin** [comment]
@Snorch could you rebase this pr

**Comment by Snorch** [comment]
Done.

**Comment by Snorch** [comment]
Rebase again and gentle ping. Any news? @adrianreber @xemul

**Pull request merged**
