### PR TITLE
seize: restore cgroup freezer to right state

### PR DESCRIPTION
**Pull request by liusdu**
Now if criu dump failed before freezing dumpee, criu always freeze
dumpee in cr_dump_finish.

Signed-off-by: Liu Hua <weldonliu@tencent.com>

### CODE REVIEW

**Comment by Snorch** [comment]
I believe that this patch introduces code change which does not change semantics. -> Nack.

```
        state = get_freezer_state(fd);
# here state can be one of FREEZER_ERROR, THAWED, FROZEN, FREEZING
        if (state == FREEZER_ERROR) {
                close(fd);
                return -1;
        }
# here state can be one of THAWED, FROZEN, FREEZING
-       if (state == THAWED) {
-               freezer_thawed = true;
# so (freezer_thawed == true) is equivalent to (state == THAWED) or ((state != FROZEN) && (state != FREEZING))
 
+       freezer_state = state == FREEZING ? FROZEN : state;
# and (freezer_state == THAWED) is equivalent to (state == THAWED)
# and (freezer_state != FROZEN) is equivalent to ((state != FROZEN) && (state != FREEZING))
+
+       if (state == THAWED) {
```

Meaning that (freezer_thawed == true) and (freezer_state == THAWED) and (freezer_state != FROZEN) all are equivalents.

**Review by Snorch — APPROVED** [review]
> I believe that this patch introduces code change which does not change semantics. -> Nack.
> 
> ```
>         state = get_freezer_state(fd);
> # here state can be one of FREEZER_ERROR, THAWED, FROZEN, FREEZING
>         if (state == FREEZER_ERROR) {
>                 close(fd);
>                 return -1;
>         }
> # here state can be one of THAWED, FROZEN, FREEZING
> -       if (state == THAWED) {
> -               freezer_thawed = true;
> # so (freezer_thawed == true) is equivalent to (state == THAWED) or ((state != FROZEN) && (state != FREEZING))
>  
> +       freezer_state = state == FREEZING ? FROZEN : state;
> # and (freezer_state == THAWED) is equivalent to (state == THAWED)
> # and (freezer_state != FROZEN) is equivalent to ((state != FROZEN) && (state != FREEZING))
> +
> +       if (state == THAWED) {
> ```
> 
> Meaning that (freezer_thawed == true) and (freezer_state == THAWED) and (freezer_state != FROZEN) all are equivalents.

Ah, big sorry, looks I'm wrong, the initial value is what you've actually changed. Now it looks reasonable for me.

**Comment by liusdu** [comment]
@Snorch yes, The actual change of this commit is the  initial value and it is enough for the bug I met.  Some functions using this variable maybe  need to be changed, but I have no idea about the influence.. Should I dig it up？

**Comment by Snorch** [comment]
> @Snorch yes, The actual change of this commit is the initial value and it is enough for the bug I met.

Please add a note about it in the commit message. It would be useful to know not only what problem you solve but also how you solve it https://github.com/checkpoint-restore/criu/blob/criu-dev/CONTRIBUTING.md#describe-your-changes.
```
Once the problem is established, describe what you are actually doing
about it in technical detail.
```

> Some functions using this variable maybe need to be changed, but I have no idea about the influence.. Should I dig it up？

AFAICS you did everything right, no change needed, that's why I approved the PR.

**Comment by avagin** [comment]
LGTM

**Comment by Snorch** [comment]
@liusdu Please change description to something like
```
The new freezer_state is a complete equivalent of old freezer_thawed
except for the initial value. If old freezer_thawed was not initialized
it was 0 and in freezer_restore_state were threated as if we need to
freeze cgroup "back", thus before this patch if criu dump failed before
freezing dumpee, criu always freeze dumpee in cr_dump_finish which is
wrong. Switching to freezer_state initialized with FREEZER_ERROR fixes
the problem.
```

And also please rename freezer_state to origin_freezer_state, because having same variable name with enum name makes grepping it harder.

**Comment by Snorch** [comment]
I've updated the PR myself, will merge when tests would pass.

**Review by Snorch — APPROVED** [review]

**Comment by liusdu** [comment]
@Snorch  Thanks～

**Pull request merged**
