### PR TITLE
MAINTAINERS: Add Radostin (myself) to maintainers

### PR DESCRIPTION
**Pull request by rst0git**
I've been contributing to CRIU for sometime and I'm hoping that my familiarity with the project would be sufficient to self-nominate as a maintainer. I would like to help with code reviews, submitting patches, implementing new features, and maintaining the project in general.

### CODE REVIEW

**Comment by avagin** [comment]
lgtm

**Review by xemul — APPROVED** [review]
Welcome!

**Review by rppt — APPROVED** [review]

**Review by adrianreber — APPROVED** [review]

**Review by 0x7f454c46 — COMMENTED** [review]
LGTM, welcome!

**Comment by Snorch** [comment]
LGTM =)

**Pull request merged**
