### PR TITLE
Add go_package option for go bindings to .proto files

### PR DESCRIPTION
**Pull request by Pac23**
To port crit to go the pb.go bindings need to be generated. For bindings to be in a single package to avoid explicit import of all the pb.go files.

To achieve this option go_package = "/package-name"; has been added to the .proto files.

### CODE REVIEW

**Comment by avagin** [comment]
"""
 The `.proto` file should contain a go_package option specifying the full import path of the Go package that contains the generated code.
"""
https://developers.google.com/protocol-buffers/docs/reference/go-generated

If I understand this right, go_package should be "https://github.com/checkpoint-restore/criu/something".

**Comment by adrianreber** [comment]
As we are using `go-criu` as our Go bindings repository it should probably point to `go-criu`.

**Comment by Pac23** [comment]
> """
> The `.proto` file should contain a go_package option specifying the full import path of the Go package that contains the generated code.
> """
> https://developers.google.com/protocol-buffers/docs/reference/go-generated
> 
> If I understand this right, go_package should be "https://github.com/checkpoint-restore/criu/something".

i was thinking more in terms of having these generated by makefile locally thus the "/packagename"

**Comment by avagin** [comment]
> i was thinking more in terms of having these generated by makefile locally thus the "/packagename"

I don't understand this. Do you have code that imports "/packagename"?

**Comment by Pac23** [comment]
> > i was thinking more in terms of having these generated by makefile locally thus the "/packagename"
> 
> I don't understand this. Do you have code that imports "/packagename"?

yes, so how i thought of this is during installation/make of the go port of CRIT generate the pb.go files locally from the proto files in criu/images.

**Comment by avagin** [comment]
Can you show how the code which imports /packagename looks like?

**Comment by avagin** [comment]
The criu-dev branch has been force-pushed. Please rebase this PR.

**Comment by Pac23** [comment]
> The criu-dev branch has been force-pushed. Please rebase this PR.

Sure,thanks for letting me know :)

**Comment by Pac23** [comment]
cross refrencing https://github.com/checkpoint-restore/go-criu/pull/30

**Comment by adrianreber** [comment]
I am closing this as there is currently no one working on it.

**Pull request closed without merging**
