### PR TITLE
Prepare 3.14 (part3)

### PR DESCRIPTION
**Pull request by avagin**
* Add time namespace support
* A few fixes here and there

### CODE REVIEW

**Comment by avagin** [comment]
This is the final part.

**Comment by avagin** [comment]
https://criu.org/Download/criu/3.14

**Comment by avagin** [comment]
I suggest @nviennot to choose the name for this release. The format is "material"/"bird breed". Here is the list of all previous releases https://criu.org/Download/criu

**Comment by nviennot** [comment]
I'm happy and honoured to pick a name!
How about **Platinum Peacock**

**Comment by avagin** [comment]
> How about Platinum Peacock

Sounds good to me. I like that it is something real:

white-peacock

**Comment by kolyshkin** [comment]
@avagin can you maybe add https://github.com/checkpoint-restore/criu/pull/1033? It's cosmetic but soft of important for runc integration tests.

**Pull request merged**
