### PR TITLE
Issue #349: Create man page for libcompel

### PR DESCRIPTION
**Pull request by harshanavkis**

### CODE REVIEW

**Comment by adrianreber** [comment]
Thanks for the pull request. Can you please add a Signed-off-by (git commit -s --amend) and force push.

**Comment by rst0git** [comment]
@harshanavkis thank you for opening this PR. In addition to Signed-off-by, most of CRIU commits tend to identify which area or subsystem is being patched in the commit message (see `git log --oneline`). Thus, a better commit message could be:
```
Documentation: Create man page for libcompel

Resolves #349
```

**Comment by harshanavkis** [comment]
https://github.com/checkpoint-restore/criu/pull/724#issue-290815582

**Comment by avagin** [comment]
Dup of https://github.com/checkpoint-restore/criu/pull/724

**Pull request closed without merging**
