### PR TITLE
RCF: Clang format improve human readability with "comment" allignment

### PR DESCRIPTION
**Pull request by Snorch**
There are many places where we had intentionally short alligned lines for human readability, to be able to resurect those places we can use the hack with adding comments at the end of line where we don't want the break-line to collapse.

I want to understand if this solution is ok for us or not. Didn't find a better way with clang.

v2: switched to simple clang-format disabling instead of comments.

### CODE REVIEW

**Comment by Snorch** [comment]
Please I need some suggestions on this, alternatively we can just disable clang in such places https://github.com/Snorch/criu/commit/692b21e5ae1187b7f51a0c0d9f58c45824d52866

**Comment by Snorch** [comment]
@checkpoint-restore/maintainers

**Comment by adrianreber** [comment]
Both solutions (comments or disabling clang-format for the section) work for me.

**Comment by rppt** [comment]
> Please I need some suggestions on this, alternatively we can just disable clang in such places [Snorch@692b21e](https://github.com/Snorch/criu/commit/692b21e5ae1187b7f51a0c0d9f58c45824d52866)

I like this one more

**Comment by rst0git** [comment]
> > Please I need some suggestions on this, alternatively we can just disable clang in such places [Snorch@692b21e](https://github.com/Snorch/criu/commit/692b21e5ae1187b7f51a0c0d9f58c45824d52866)
> 
> I like this one more

Me too.

**Review by rst0git — APPROVED** [review]

**Comment by Snorch** [comment]
> > > Please I need some suggestions on this, alternatively we can just disable clang in such places [Snorch@692b21e](https://github.com/Snorch/criu/commit/692b21e5ae1187b7f51a0c0d9f58c45824d52866)
> > 
> > 
> > I like this one more
> 
> Me too.

Note that the way with comments has an advantage of still checking everything else clang-format related except wrapping on binary operator. But as we don't plan to change style much regions with clang format off should also be fine.

**Pull request merged**
