### PR TITLE
Move timers dump/restore code into separate file

### PR DESCRIPTION
**Pull request by rakki-18**
This tries to solve the issue #335 
The set of functions starting from ```prepare_itimers()``` to ```prepare_posix_timers``` was removed from ```criu/cr-restore.c``` and added to a new file ```criu/prepare_timers.c``` 
and similarly the set of functions starting from ```parasite_dump_itimers_seized``` to parasite_dump_posix_timers_seized``` was removed from ```criu/parasite-syscall.c``` and added to a new file ```criu/timers.c``` .
@xemul could you please review and check if this solves the issue or if I have to make changes ?

### CODE REVIEW

**Comment by adrianreber** [comment]
@rakki-18 This pull request has multiple problems:

 * You included binary files in the commit which do not belong here (protoc)
 * The complete x86_64-linux-gnu directory does not belong in the pull request
 * All generated files do not belong in the pull request. These files should be generated during build-time
 * CI fails completly
 * All your comments have almost the same description. Each commit should have its own complete description about the changes in the commit
 * There should be no merge commits in your pull request
 * None of the commits are correctly signed off: https://github.com/checkpoint-restore/criu/blob/criu-dev/CONTRIBUTING.md

**Comment by rakki-18** [comment]
@adrianreber Thanks for reviewing. I'll try to fix the problems .

**Comment by rakki-18** [comment]
1. From ```criu/cr-restore.c``` , I have to remove  the functions ```prepare_itimers_from_fd()``` ,    ```prepare_itimers()``` ,  ```timespec_valid()``` , ```decode_posix_timer()``` , ```cmp_posix_timer_proc_id()``` , ```sort_posix_timers()```  and the function declaration ```static int prepare_itimers(int pid, struct task_restore_args *args, CoreEntry *core);```  and add them to a new .c file  right ?
2. When I add them to a new .c file in the criu/ directory, should I include all the header files of ```criu/cr-restore.c``` in the new .c file ?

**Comment by adrianreber** [comment]
>     1. From `criu/cr-restore.c` , I have to remove  the functions `prepare_itimers_from_fd()` ,    `prepare_itimers()` ,  `timespec_valid()` , `decode_posix_timer()` , `cmp_posix_timer_proc_id()` , `sort_posix_timers()`  and the function declaration `static int prepare_itimers(int pid, struct task_restore_args *args, CoreEntry *core);`  and add them to a new .c file  right ?

Cannot answer that.

>     2. When I add them to a new .c file in the criu/ directory, should I include all the header files of `criu/cr-restore.c` in the new .c file ?

No, only the ones you actually need.

**Pull request closed without merging**
