### PR TITLE
criu: Version 3.17

### PR DESCRIPTION
**Pull request by adrianreber**
Amongst a huge number of fixes all over the place this release introduces:

* mount-v2 engine
* support for MAP_HUGETLB mappings
* support for Linux Restartable Sequences
* support for SOCK_SEQPACKET unix sockets
* CRIU AMD GPU plugin
* setsockopt(SO_BUF_LOCK) support for tcp sockets

@checkpoint-restore/maintainers this are the `Makefile.versions` changes for release 3.17. PTAL.

### CODE REVIEW

**Comment by adrianreber** [comment]
I see a couple of new failures with `static/bridge`:
```
2022-05-01T16:00:16.9754754Z ======================== Run zdtm/static/bridge in uns =========================
2022-05-01T16:00:16.9754999Z Start test
2022-05-01T16:00:16.9755188Z Test is SUID
2022-05-01T16:00:16.9755495Z ./bridge --pidfile=bridge.pid --outfile=bridge.out
2022-05-01T16:00:16.9755743Z Run criu dump
2022-05-01T16:00:16.9755985Z Wait for zdtm/static/bridge(87) to die for 0.100000
2022-05-01T16:00:16.9756353Z Run criu restore
2022-05-01T16:00:16.9756665Z =[log]=> dump/zdtm/static/bridge/87/1/restore.log
2022-05-01T16:00:16.9757064Z ------------------------ grep Error ------------------------
2022-05-01T16:00:16.9757444Z b'(00.006251)      1: Try to restore a link 10:2:zdtmbr0'
2022-05-01T16:00:16.9757775Z b'(00.006256)      1: Restoring link zdtmbr0 type 6'
2022-05-01T16:00:16.9758118Z b'(00.006262)      1: Restoring netdev zdtmbr0 idx 2'
2022-05-01T16:00:16.9758467Z b'(00.006269)      1: Restore ll addr (c6:../6) for device'
2022-05-01T16:00:16.9758914Z b'(00.006300)      1: Error (criu/libnetlink.c:54): -95 reported by netlink: Operation not supported'
2022-05-01T16:00:16.9759357Z b"(00.006304)      1: Error (criu/net.c:1816): Can't restore link: -95"
2022-05-01T16:00:16.9759806Z b"(00.006404)      1: Error (criu/util.c:1411): Can't wait or bad status: errno=0, status=65280"
2022-05-01T16:00:16.9760184Z b'(00.006841) uns: calling exit_usernsd (-1, 1)'
2022-05-01T16:00:16.9760514Z b'(00.006875) uns: daemon calls 0x476140 (117, -1, 1)'
2022-05-01T16:00:16.9760828Z b'(00.006886) uns: `- daemon exits w/ 0'
2022-05-01T16:00:16.9761131Z b'(00.007517) uns: daemon stopped'
2022-05-01T16:00:16.9761475Z b'(00.007524) Error (criu/cr-restore.c:2536): Restoring FAILED.'
2022-05-01T16:00:16.9761868Z ------------------------ ERROR OVER ------------------------
2022-05-01T16:00:16.9762200Z ################# Test zdtm/static/bridge FAIL at CRIU restore #################
```

The main difference between the working CI runs and the none working CI runs is that the CI kernel has been upgraded from `Linux 5.13.0-1021-azure #24~20.04.1-Ubuntu SMP Tue Mar 29 15:34:22 UTC 2022 x86_64` to `5.13.0-1022-azure #26~20.04.1-Ubuntu SMP Thu Apr 7 19:42:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`.

I cannot reproduce on Fedora's 5.16.18. As the failure is in Arch and Fedora Rawhide maybe it is a combination of newer libnl3 and that specific kernel.

The Podman test seems to be failing because `crun` picks up the installed CRIU (`/usr`)and not the one from our CI run (`/usr/local`).

**Comment by avagin** [comment]
@adrianreber could you take a look at why presubmit checks failed?
@mihalicyn What does Mr. Jenkins think about this release?

**Comment by adrianreber** [comment]
Updated this PR with three patches to fix CI failures.

**Comment by mihalicyn** [comment]
@adrianreber please take changes from these PRs:
https://github.com/checkpoint-restore/criu/pull/1871
https://github.com/checkpoint-restore/criu/pull/1869

**Comment by adrianreber** [comment]
> @adrianreber please take changes from these PRs: #1871 #1869

I added the three commits.

**Comment by adrianreber** [comment]
@avagin Please rebase `criu-dev` on top of `master`.

**Comment by li-xiaocheng** [comment]
hello! now criu support amd gpu， nvidia gpu when can it be supported？

**Comment by adrianreber** [comment]
> hello! now criu support amd gpu， nvidia gpu when can it be supported？

As soon as somebody writes the patches to support it.

**Pull request merged**
