### PR TITLE
ci: update to latest Vagrant and Fedora images

### PR DESCRIPTION
**Pull request by adrianreber**
update to latest Vagrant and Fedora images

### CODE REVIEW

**Comment by adrianreber** [comment]
Running on Fedora 35 introduces new failures as Fedora 35 is based on btrfs. Once #1673 is merged I will take a closer look.

**Comment by avagin** [comment]
@mihalicyn can help with btrfs failures.

**Comment by Snorch** [comment]
Hm, btrfs gives different device numbers in mountinfo and in stat...
```
[snorch@fedora ~]$ stat /home/
  File: /home/
  Size: 12              Blocks: 0          IO Block: 4096   directory
Device: 29h/41d Inode: 256         Links: 1
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:home_root_t:s0
Access: 2021-12-16 11:50:28.332715403 +0300
Modify: 2021-07-22 02:47:06.000000000 +0300
Change: 2021-12-08 13:17:25.474113812 +0300
 Birth: 2021-05-15 00:37:04.044971763 +0300
[snorch@fedora ~]$ grep home /proc/self/mountinfo
94 65 0:33 /home /home rw,relatime shared:46 - btrfs /dev/nvme0n1p3 rw,seclabel,compress=zstd:1,ssd,space_cache,subvolid=256,subvol=/home
```
41 != 33

In stat btrfs_getattr() puts BTRFS_I(inode)->root->anon_dev and in mountinfo kernel prints sb->s_dev. That's why __open_mountpoint fails to check that it opened the right mount...

**Comment by Snorch** [comment]
@adrianreber All zdtm tests pass on F35 for me on my laptop with this fix https://github.com/checkpoint-restore/criu/pull/1692 Please check if it also helps with your PR.

**Comment by adrianreber** [comment]
> @adrianreber All zdtm tests pass on F35 for me on my laptop with this fix #1692 Please check if it also helps with your PR.

Cool. Thanks a lot. I am working with @rst0git to see what we can do about the rawhide failures. We are currently assuming it is related to a glibc update.

**Comment by adrianreber** [comment]
@Snorch I added your btrfs commits to this PR for testing and it seems all btrfs related failures are gone. Looks good. Thanks.

**Review by rst0git — APPROVED** [review]
LGTM

**Pull request merged**
