### PR TITLE
Add support for python3 in criu-coredump

### PR DESCRIPTION
**Pull request by AndreyVV-100**
Add support for python3 in criu-coredump, while retaining support for python2. On a snapshot of a small C program, coredump-python2 and coredump-python3 produced identical results (also checked readelf output of the resulting coredump). ZDTM tests not run (currently not working on my machine).

### CODE REVIEW

**Comment by adrianreber** [comment]
Thanks for the PR. I think that was our last Python 2 only code. I think we do not run coredump tests anywhere in CI. Can you also enable criu-coredump tests in CI so that we do not break it in the future.

**Comment by adrianreber** [comment]
Oh, and add the criu-coredump files to the lint target so that the files follow the coding guidelines if possible.

**Comment by AndreyVV-100** [comment]
Thanks for the review. I am not familiar with CI scripting (nor how it is set up in criu), where should I look?

Regarding lint (assuming you mean ```make lint```), I see that ```flake8``` flags many pre-existing issues in ```coredump.py``` and ```elf.py``` if I run it manually:

In ```coredump.py```:
```
coredump.py:223:9: E265 block comment should start with '# '
coredump.py:322:9: E303 too many blank lines (2)
coredump.py:346:9: E265 block comment should start with '# '
coredump.py:414:9: E265 block comment should start with '# '
coredump.py:588:28: E262 inline comment should start with '# '
coredump.py:655:52: E712 comparison to True should be 'if cond is True:' or 'if cond:'
coredump.py:659:80: E501 line too long (82 > 79 characters)
coredump.py:675:13: E265 block comment should start with '# '
coredump.py:679:13: E265 block comment should start with '# '
coredump.py:725:18: E711 comparison to None should be 'if cond is not None:'
coredump.py:728:25: E711 comparison to None should be 'if cond is not None:'
coredump.py:755:14: E711 comparison to None should be 'if cond is not None:'
coredump.py:790:14: E127 continuation line over-indented for visual indent
coredump.py:793:14: E127 continuation line over-indented for visual indent
coredump.py:794:14: E127 continuation line over-indented for visual indent
coredump.py:795:14: E127 continuation line over-indented for visual indent
coredump.py:834:13: F841 local variable 'size' is assigned to but never used
```

In ```elf.py```:  273 warnings.

Is it really alright to add them to ```make lint``` in this state?

**Comment by adrianreber** [comment]
> Thanks for the review. I am not familiar with CI scripting (nor how it is set up in criu), where should I look?
> 
> Regarding lint (assuming you mean `make lint`), I see that `flake8` flags many pre-existing issues in `coredump.py` and `elf.py` if I run it manually:
> 
> In `coredump.py`:
> 
> ```
> coredump.py:223:9: E265 block comment should start with '# '
> coredump.py:322:9: E303 too many blank lines (2)
> coredump.py:346:9: E265 block comment should start with '# '
> coredump.py:414:9: E265 block comment should start with '# '
> coredump.py:588:28: E262 inline comment should start with '# '
> coredump.py:655:52: E712 comparison to True should be 'if cond is True:' or 'if cond:'
> coredump.py:659:80: E501 line too long (82 > 79 characters)
> coredump.py:675:13: E265 block comment should start with '# '
> coredump.py:679:13: E265 block comment should start with '# '
> coredump.py:725:18: E711 comparison to None should be 'if cond is not None:'
> coredump.py:728:25: E711 comparison to None should be 'if cond is not None:'
> coredump.py:755:14: E711 comparison to None should be 'if cond is not None:'
> coredump.py:790:14: E127 continuation line over-indented for visual indent
> coredump.py:793:14: E127 continuation line over-indented for visual indent
> coredump.py:794:14: E127 continuation line over-indented for visual indent
> coredump.py:795:14: E127 continuation line over-indented for visual indent
> coredump.py:834:13: F841 local variable 'size' is assigned to but never used
> ```
> 
> In `elf.py`: 273 warnings.
> 
> Is it really alright to add them to `make lint` in this state?

No, unless you would be willing to fix those warnings :wink:

**Comment by rst0git** [comment]
> I am not familiar with CI scripting (nor how it is set up in criu), where should I look?

You can add the following line in the [Makefile](https://github.com/checkpoint-restore/criu/blob/9819df78e07ec44d6b81064f8148ebac0ce052c5/Makefile#L421):
```
flake8 --config=scripts/flake8.cfg coredump/
```

**Comment by amonakov** [comment]
@rst0git, as discussed with @adrianreber above, it is not appropriate to add flake8 checks for coredump files at this time (too many preexisting warnings).

I suggested this to Andrey a few weeks ago as a "warm-up" task of a larger assignment for his summer practice work, to build up some familiarity with python-based part of CRIU (the rest of his work was not related to Python). I think for now it's better to focus on proposed Python changes. Do they all look good to you?

**Comment by rst0git** [comment]
@amonakov Thank you for letting me know. I've opened a PR (https://github.com/checkpoint-restore/criu/pull/1605) to extend the proposed changes by resolving the outstanding issues to enable flake8 checks and CI tests for coredump. I hope this helps.

**Comment by adrianreber** [comment]
@AndreyVV-100 Around line 277 in `scripts/ci/run-ci-tests.sh` there is the following line
```
make -C test/others/crit run
```
Just add a corresponding line for criu-coredump.

**Comment by rst0git** [comment]
> Just add a corresponding line for criu-coredump.

I've enabled this in https://github.com/checkpoint-restore/criu/pull/1605/commits/cf468a7774f27614e4699704752edeae6d354afc

**Comment by adrianreber** [comment]
> > Just add a corresponding line for criu-coredump.
> 
> I've enabled this in [cf468a7](https://github.com/checkpoint-restore/criu/commit/cf468a7774f27614e4699704752edeae6d354afc)

I would prefer to have CI results available already in this PR if they pass. I know that it currently does not work with Python 3 at all, but if this PR fixes this, we could already enable CI runs in this PR to know that the PR really fixes it.

**Comment by adrianreber** [comment]
This has been merged via #1605. Thanks.

**Pull request closed without merging**
